# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: ğŸ“ Pull Request Action

on:
  # push:
  #   branches: [main]
  pull_request:
    # branches: [main]
    types:
      - opened
      - edited
      - synchronize
      - reopened
    # workflow_call:

jobs:
  build:
    name: 'ğŸ— Build Application'
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
    # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - name: 'â˜ checkout repository'
        uses: actions/checkout@v2

      - name: 'ğŸ’¾ Use Node.js 16'
        uses: actions/setup-node@v2
        with:
          node-version: ${{matrix.node-version}}
          cache: 'yarn'

      - name: 'ğŸ“ƒ Install dependencies'
        uses: bahmutov/npm-install@v1.6.0
      # - run: yarn install

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-out name=dir::$(yarn cache dir)"

      - name: ğŸš§ Start Caching Build
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: |
            ~/.yarn
            ${{ github.workspace }}/.next/cache

          key: ${{runner.os}}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: ğŸ Yarn build if cache is stale
        run: yarn build

      # - name: ğŸŒ© Upload artifact
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: build-artifact
      #     path: |
      #       ~/.yarn
      #       ${{ github.workspace }}/.next/cache
      #     if-no-files-found: ignore

  # Cypress testing
  test:
    name: Cypress Testing Phase
    runs-on: ubuntu-latest
    needs:
      - build
    # strategy:
    #   matrix:
    #     node-version: [16.x]

    steps:
      - name: â›… checkout repository
        uses: actions/checkout@v2

      - name: ğŸ–¥ Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: yarn

      # - name: ğŸ“© Download Artifact
      #   uses: actions/download-artifact@v3
      #   with:
      #     name: build-artifact

      - name: 'ğŸ“ƒ Install dependencies'
        uses: bahmutov/npm-install@v1.6.0

      - name: ğŸš§ Start Caching Build
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: |
            ~/.yarn
            ${{ github.workspace }}/.next/cache

          key: ${{runner.os}}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: ğŸ§ª Run all tests
        uses: cypress-io/github-action@v2
        with:
          browser: chrome
          headless: true

      # - name: ğŸŒ  Display structure of downloaded file
      #   run: ls -R

  # steps:
